### ISSUE TITLE
Bugs on Firefox since today

### ISSUE THREAD

**Issue by xem** [domoritz/himawari-8-chrome#2]
domoritz.de/himawari-8-chrome/ worked perfectly on firefox until today. Is it possible to fix it please?

**Comment by domoritz** [comment]
Thank you for reporting the issue. I've fixed it in https://github.com/domoritz/himawari-8-chrome/commit/90234d62a4202aab5c769b60a92ee0330f35f855. I'll test in different browsers in the future.
