### ISSUE TITLE
URL not selected in new tab in some cases

### ISSUE THREAD

**Issue by cmur2** [domoritz/himawari-8-chrome#21]
A Firefox user here: whenever I have something selected in the URL bar in my currently open tab and I open a new tab (with this great addon installed) the cursor is just at the end of `moz-extension://3a19d073-9ca7-4106-b212-5206efe15c50/index.html` without the text being selected.

Can this be solved somehow?

**Comment by domoritz** [comment]
Yes, I found it super annoying as well. It is a problem with Firefox that I believe was fixed in 57. You can track the bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1373613.
