### ISSUE TITLE
CORS issue with DSCOVR EPIC option

### ISSUE THREAD

**Issue by chrishutchinson** [domoritz/himawari-8-chrome#22]
Hey, 

I could be wrong, but in the Firefox extension (can't confirm if this is the same for Chrome) if I choose DSCOVR EPIC the image doesn't load in my new tab. Looking at the console, I get a CORS error with the [EPIC API](https://epic.gsfc.nasa.gov/about/api).

<img width="466" alt="screen shot 2018-02-02 at 10 57 30" src="https://user-images.githubusercontent.com/1573022/35729843-e24b9566-0807-11e8-922d-eb3d4d411b6c.png">

Looking at the docs under "API Mirroring and CORS Support", it appears that `api.nasa.gov` provides a CORS-supported proxy for the EPIC API, would it make sense to swap to that?

Happy to contribute if so, but wanted to check in first!

**Comment by chrishutchinson** [comment]
Hm, this appears that it may have been a glitch, and is now working as expected. I'll close this for now, but will keep an eye on it in case it happens again!

**Comment by domoritz** [comment]
Ahh, I didn't know about the API and should definitely switch to the official way. 

@chrishutchinson thanks for reporting the issue and pointing me to the API
