### ISSUE TITLE
Meteosat imagery

### ISSUE THREAD

**Issue by erget** [domoritz/himawari-8-chrome#26]
Any plans to include the option to download Meteosat imagery?

**Comment by domoritz** [comment]
Is there a good data source for the images? It's fairly straight forward to add another data source but I want it to be reliable.

**Comment by domoritz** [comment]
We need a download url for the images and a document that tells uw what the latest image is.

**Comment by domoritz** [comment]
http://oiswww.eumetsat.org/IPPS/html/MSGIODC/RGB/NATURALCOLOR/FULLDISC/index.htm could work

**Comment by domoritz** [comment]
Okay, the low resolution images are all at http://oiswww.eumetsat.org/IPPS/html/latestImages.html so we could use that but it's really low quality (http://oiswww.eumetsat.org/IPPS/html/latestImages/EUMETSAT_MSG_RGBNatColour_LowResolution.jpg).

For high resolution images, they generate secret URLs that are not easy to access: http://oiswww.eumetsat.org/IPPS/html/MSGIODC/RGB/NATURALCOLOR/FULLRESOLUTION/. @erget, do you know how we can figure out the high resolution URLs like http://oiswww.eumetsat.org/IPPS/html/MSGIODC/RGB/NATURALCOLOR/FULLRESOLUTION/IMAGESDisplay/sLdkTbgeOPSi9?

**Comment by domoritz** [comment]
The hacky solution would be to scrape https://cors-anywhere.herokuapp.com/http://oiswww.eumetsat.org/IPPS/html/MSG/RGB/NATURALCOLOR/FULLRESOLUTION/index.htm' and get the token but that doesn't seem great. Let me know if you know a better way!

**Comment by erget** [comment]
I used to download from http://oiswww.eumetsat.org/IPPS/html/MSGIODC/RGB/NATURALCOLOR/FULLDISC/index.htm using selenium and scrape out the image, like this: https://gist.github.com/erget/9e356ea4bef4b653f51f7699017cd7a4

It's very far from elegant but it did the job back in the day :)

**Comment by domoritz** [comment]
Oh sweet. We only need the URL so this should be sufficient:

```py
URL = "http://oiswww.eumetsat.org/IPPS/html/MSG/RGB/NATURALCOLOR/FULLRESOLUTION/index.htm"

def get_current_meteosat():
    """Download current Meteosat 0 full disc view."""
    browser = webdriver.PhantomJS()
    browser.get(URL)
    img_element = browser.find_element_by_name("mainImage")
    img_url = img_element.get_attribute("src")
    browser.quit()
    return img_url
```

Do you know a good place to run this as a web service somewhere?

**Comment by domoritz** [comment]
Would you want to send a PR to add Meteosat? Once there is a way to get the image URL, it should be fairly straight forward.

**Comment by erget** [comment]
I'll take a look and try to fire off a PR tonight.

**Comment by erget** [comment]
Been a while since I worked with node... In the README you say that you can fire it up with ``npm run dev``, but I don't see ``dev`` among the start scripts. I also don't see the mentioned ``pack.sh``. Am I missing something?

I also saw that you have a new branch with my code copied in and some scaffolding, but I think that prototype-type code might not be too good - it requires that ``phantomjs`` is installed, which is now as I take it deprecated. So I'd be happy to use a headless Chrome or similar instead, but I'm not sure how to integrate this into your app.

Sorry for the noob questions! If you point me in the right direction, I'll hammer away at it again.

**Comment by domoritz** [comment]
Ups, the instructions were out of date. I updated them.

Yes, I was hoping to run your code on Appengine but it didn't work at all. Since all we need is the last bit of the URL (in the code it is `array_nom_imagen[0]`, we could try to just write a regex that runs over the raw HTML.

**Comment by domoritz** [comment]
I have to debug appengine a bit more but https://github.com/domoritz/himawari-8-chrome/blob/meteosat/main.py is what I'm thinking.

**Comment by domoritz** [comment]
Here we go: https://meteosat-url.appspot.com/

```json
{
  "url": "http://oiswww.eumetsat.org/IPPS/html/MSGIODC/RGB/NATURALCOLOR/FULLRESOLUTION/IMAGESDisplay/crsHR6w1etpik",
  "date": "2018-06-19 20:00:00"
}
```

**Comment by domoritz** [comment]
Now we only also need the timestamp and add some caching.

**Comment by domoritz** [comment]
But you can start on the javascript side with this.

**Comment by domoritz** [comment]
I added some memcache caching so that we don't make too many requests.

**Comment by erget** [comment]
Brilliant, understood. So I grok the Python now. Just got back - at a conference now so availability is low, I'll try again tomorrow to get the JS side running under master.

**Comment by erget** [comment]
Alright, next hurdle - `yarn start` reports:
```
$ python -m http.server
Done in 0.24s.
```

But then localhost:8000 is unreachable. I tried fiddling around with a few different ports, but to no avail. Do you have a tip?

**Comment by erget** [comment]
Never mind, first Chrome extension for a while. I loaded it as described as an unpacked extension, everything is now fine and I can get to work.

**Comment by erget** [comment]
Another note: We could add the [Indian Ocean Data Coverage imagery](http://oiswww.eumetsat.org/IPPS/html/MSGIODC/RGB/NATURALCOLOR/FULLDISC/index.htm). Do you want to add this to the same web service, or would you have 2 which need to be called up?

**Comment by domoritz** [comment]
I'd say that we should add both to the same service but with different URLs.

**Comment by domoritz** [comment]
I added support for both: access at https://meteosat-url.appspot.com/msg  (at 0 degrees) and https://meteosat-url.appspot.com/msgiodc (at 41.5 degrees).

**Comment by domoritz** [comment]
@erget Do you need help? If you send a PR, I can have a look.

**Comment by erget** [comment]
Thanks for adding that support! I might need help but I was offline for a few days / busy with other things, so I didn't have time to keep working on it.

I'm using my Surface Tablet, which has the Linux subsystem installed, because I feel most comfortable in Linux, but when I started up my computer today it wasn't able to run Linux for some reason, and that's where I've got my development environment :( So I'm fixing that first ;)

**Comment by erget** [comment]
I'm moving discussion into PR #27 to keep it in one place.

**Comment by domoritz** [comment]
Done. 🎉

**Comment by domoritz** [comment]
@erget The chrome extension is live. The firefox version will be up tomorrow probably.
