### ISSUE TITLE
himawari-8 servers down?

### ISSUE THREAD

**Issue by adriel** [domoritz/himawari-8-chrome#326]
https://himawari-8.appspot.com/latest is giving me "502 Bad Gateway"

And https://himawari8-dl.nict.go.jp/himawari8/img/D531106/latest.json gives "ERR_CONNECTION_REFUSED", is this just on my end, or is it down for everyone?

Seems to have started some time in the last 24 hours.

**Comment by domoritz** [comment]
Thanks for the report. Even https://himawari8.nict.go.jp/ looks down to me as well. I don't see an alternative source so I guess we just have to wait it out. You can change to another source in the meantime. 

Not sure why my proxy didn't cache the latest request. Feel free to take a look at https://github.com/domoritz/himawari-8-chrome/blob/proxy/main.go.

**Comment by adriel** [comment]
Looks to be back up.
